### ISSUE TITLE
Deity: As a dev, I want a single callable object to handle the deity/cron game tick.

### ISSUE THREAD

**Issue by Beagle** [BitLucid/ninjawars#235]
Currently, all game tick logic is in procedural automation in deploy/cron/deity_*.php. 
A single co-ordinating object will encapsulate the logic and the many deity_*.php scripts will simply be replaced by the object.

AC:
- No deity functions.
- A single deity object.
- Different intervals are still handled correctly. (not necessarily atomically)

**Comment by tchalvak** [comment]
:+1:

**Comment by tchalvak** [comment]
The separate deity files exist because it's hard to determine, say, a 10 minute interval within a script run every 1 minute, without some kind of hack-y counter within the database or something.  But maybe we can split a single, called deity file in the cron with arguments to the command line.

http://stackoverflow.com/questions/9612166/how-do-i-pass-parameters-into-a-php-script-through-a-webpage

**Comment by tchalvak** [comment]
![screenshot from 2015-12-15 10 24 55](https://cloud.githubusercontent.com/assets/23353/11814719/53c0984e-a316-11e5-9137-3c496a9e2c77.png)

**Comment by Beagle** [comment]
It's possible that this should not be a controller due to the fact that no user agent should ever call the deity explicitly. I will take a look at a better solution.

**Comment by tchalvak** [comment]
@Beagle I took the liberty of editing the initial issue title and body to create some simple, actionable AC for creating the "object" that need not be a "controller", to put all the functionality in one place.

**Comment by tchalvak** [comment]
Closing this as fixed, split out #655 for lib_deity refactor-out-of-existence.
