### ISSUE TITLE
Remove unnecessary symlinks from root of repository

### ISSUE THREAD

**Issue by Beagle** [BitLucid/ninjawars#245]
The symlinks appear to only be there for convenience and serve no real purpose. They cause confusion or extra effort when using grep, find, and other tools.

**Comment by tchalvak** [comment]
Blarg

**Comment by tchalvak** [comment]
The purpose they serve is like bash aliases for the repository.

**Comment by Beagle** [comment]
I propose that if you find them useful, you make them yourself and don't
commit them.

**Comment by tchalvak** [comment]
I did this in the past, but then ran into issues where paths that I wrote into the codebase weren't mirrored in the directory structure.

I'll remove a few that are truly unnecessary, but generally the "core -> lib" symlink is actually representative of a rename that I didn't want to rewrite a few million lines of git history to achieve.  In other words, /lib/ should actually be called /core/, I just don't want to deal with the git fallout of that rename.

vendor/ is an actual common expectation in certain cases, so that's why that is added.

/tests/ I guess I can make untracked.
/templates/ I guess I could remove.
/check.php I can certainly remove.
