### ISSUE TITLE
Rename dev to master to more consistently match GitHub Flow

### ISSUE THREAD

**Issue by Beagle** [BitLucid/ninjawars#253]
Renaming dev to master keeps us consistent with existing conventions when using GitHub Flow

**Comment by tchalvak** [comment]
Hmmm

**Comment by tchalvak** [comment]
This request makes no sense, because github flow has a "develop" branch, here named "dev".  This is what newly developed features get merged onto.  If you mean "can we clone dev into a master branch" then I guess, but it's just going to be a commit pointing at the latest tag, it's use case is very thin in the workflow.  Maaaaaaaaaaaaaaaaaaaaaaaaaybe it has some worth for quick comparison purposes only...

**Comment by tchalvak** [comment]
master branch recreated.  It matches the latest tag, or the latest tag plus any commits about to be deployed.
