### ISSUE TITLE
Test Speed: as a developer, I want my tests to run fast.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#326]
Codecoverage is making the tests suites run more than 3 times slower.
https://codeship.com/projects/41292/builds/9277752
https://codeship.com/projects/41292/builds/9266221

**Comment by Beagle** [comment]
@tchalvak CI should only ever generate code-coverage reports if it ALSO publishes them somewhere so that they're useful. If we're not ready to set that up, we can make that a goal for enhancing CI. In the meantime, we have a few options:

1. we can modify phpunit.xml to not generate code-coverage reports automatically and instead add it as a command-line flag inside specific make recipes we want reports for (like `test-unit`)
2. we can take a CLI option to `make test` that triggers code-coverage report generation and which defaults to off so that we have to manually intervene when we want a report run
3. we can create a second phpunit.xml (phpunit-ci.xml) for CI specifically, add a make recipe for `test-ci` which explicitly includes phpunit-ci.xml, and configure the CI to run `make test-ci` instead of `make test`

Do any of these strike your fancy?

**Comment by tchalvak** [comment]
Fixed in 81d2d3e26d7ec1d5040b25689cdb8ba6fa224aff
