### ISSUE TITLE
As a user, I see all menu options available to me so I am not confused about my choices

### ISSUE THREAD

**Issue by Beagle** [BitLucid/ninjawars#367]
The rollover menu hides 9 elements and shows 3. Those 3 elements are also menu elements, but it is not obvious. The 12 elements available are not all choices available, several other choices are hidden behind the map. The whole navigation system is confusing and obfuscated.

**Comment by tchalvak** [comment]
Yeah, the menu needs work.  In general, it should probably simply become not rollover at this point.  However, on small screens the options become a problem space-wise.

With map locations, the point is to move to the grid, so we can have 3234 locations if need be, and so that players and npcs can eventually have a "currently located at" spot.  Just having a menu of all the locations to click doesn't acheive that.  The dojo kinda works this way now that autolevelling is in place.  Shrine kinda works this way now that death gives you a link to heal/resurrect by and the top bar allows click to resurrect.  So the BUY WORK HUNT links are just remaining convenience markers that may bear removal to fully move to the "map" paradigm in the future.

**Comment by tchalvak** [comment]
@beagle We should brainstorm a way to revise and replace this system by voice at some point, I'll add it to trello.

**Comment by tchalvak** [comment]
Fixed in: d065e72066bb970cf3c4de7437a8c8efd60acedd
