### ISSUE TITLE
ViewSpec: As a dev, I want either docblock @return ViewSpec to give the actual return types (e.g. @return Array|RedirectResponse ), or an actual ViewSpec obj to exist.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#627]
AC:
- Docblock @return values actually reflect reality.

**Comment by Beagle** [comment]
We need to move to HttpFoundation\StreamedResponse instead of ViewSpec https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/StreamedResponse.php
https://github.com/symfony/symfony/commit/0038d1bac4a8d2dbe83f12b6a5236e8a2161b7d9

**Comment by tchalvak** [comment]
First off, why not wrap in in our own custom namespaced object, which can extend or have whatever behavior we like, whether behaving like an array or being a StreamedResponse or whatever.  Secondly, would you like to explain what you think the benefit of "Streamed" in the StreamedResponse would be in this case?  So the response is a callback, but then wouldn't we need manual boilerplate in each callback?  And isn't this just another move towards bespoke [Silex](http://silex.sensiolabs.org/)?

**Comment by Beagle** [comment]
The reason for a StreamedResponse instead of a standard Response is that
the standard Response requires the entirety of the content to be in
memory before it can be rendered, which is a major step backwards in my
opinion. Using a StreamedResponse allows us to return an object from our
controllers of type Response that doesn't incur additional memory
overhead, which is the primary reason we aren't returning fully rendered
views from our controllers right now.

As for boilerplate, yes, we'll probably start with some kind of
boilerplate until we can figure out how to abstract it properly, but
that's not a reason to not go with proper Response objects.

As for whether or not this is going towards bespoke Silex I really have
no opinion on the matter. If we start returning meaningful responses
from our controllers, and finally eliminate all logic from /www/ then
maybe we can eliminate our router and go with Silex, presuming we're OK
with whatever support we can get for our legacy URLs.

**Comment by tchalvak** [comment]
Can you get a sample of the syntax that this approach would need (e.g. to load the Casino index or whatever), so that we/I can compare & consider the changes that would be needed to implement everywhere?

**Comment by Beagle** [comment]
I will, yes
