### ISSUE TITLE
PHP7: Update to php 7 as a codebase requirement.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#698]
We can then finally do:
- scalar type hinting in functions
- null coalescing `$temp = $array['part']['sub']['sub'] ?? null;` !
- return type declaration (if we want)

**Comment by tchalvak** [comment]
@beagle You down?

**Comment by Beagle** [comment]
Not really. None of those reasons are that compelling to me right now.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Roy R.Sent: Friday, April 8, 2016 18:33To: BitLucid/ninjawarsReply To: BitLucid/ninjawarsCc: BeagleSubject: Re: [BitLucid/ninjawars] PHP7: Update to php 7 as a codebase requirement. (#698)@beagle You down?

—You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub

**Comment by tchalvak** [comment]
I am excited about the null coalescing operator, and think that scalar type hints will make some things simpler (ideally).
Php 5.6 is only actively supported through the end of 2016: http://php.net/supported-versions.php

**Comment by tchalvak** [comment]
Though it has security support thereafter.

**Comment by tchalvak** [comment]
The server is actually currently running 5.5, which is totally EOL in July.

**Comment by Beagle** [comment]
Because you're on ubuntu lts which is pretty far back                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Roy R.Sent: Saturday, April 9, 2016 06:55To: BitLucid/ninjawarsReply To: BitLucid/ninjawarsCc: BeagleSubject: Re: [BitLucid/ninjawars] PHP7: Update to php 7 as a codebase requirement. (#698)The server is actually currently running 5.5, which is totally EOL in July.

—You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub

**Comment by tchalvak** [comment]
Because I'm on 5.5, which is a number less that 5.6, and (~?2) numbers less
than 7.0.  If the default stable was 7.0 for the OS, then the nw codebase
would already be using it.

On Sat, Apr 9, 2016 at 10:02 AM, Beagle <notifications@github.com> wrote:

> Because you're on ubuntu lts which is pretty far back From: Roy R.Sent:
> Saturday, April 9, 2016 06:55To: BitLucid/ninjawarsReply To:
> BitLucid/ninjawarsCc: BeagleSubject: Re: [BitLucid/ninjawars] PHP7: Update
> to php 7 as a codebase requirement. (#698)The server is actually currently
> running 5.5, which is totally EOL in July.
>
>
> —You are receiving this because you were mentioned.Reply to this email
> directly or view it on GitHub
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BitLucid/ninjawars/issues/698#issuecomment-207793844>
>



-- 
+++++++++++++++++++++++++++
BitLucid.com <http://bitlucid.com/> - BitLucid, Inc. - Web & Programming
Consultants
ninjawars.net - My webgame project
github.com/tchalvak/ninjawars - My open source projects
dnaexmosn.deviantart.com - Art Gallery
585-519-7658  - Cell
"Never compare your inside with somebody's outside."
