### ISSUE TITLE
As a developer I want a more accurate folder structure

### ISSUE THREAD

**Issue by Beagle** [BitLucid/ninjawars#759]
/deploy/ -> /src/
  /lib/ -> /app/
  /control/ -> /controllers/
  /data/ -> /models/
  /environment/ -> /bootstrap/

**Comment by tchalvak** [comment]
Changing deploy changes all history.

**Comment by tchalvak** [comment]
(to clarify, I'm not against it in general [I'd especially like to shorten the pathing to get to stuff in deploy/tests/ and in deploy/lib/etc/], explored migrating lib to core and doing some of what you're referring to already but decided against it because of that big downside of preserving history and the problems that come from when major folders are deleted between historical git commits)

**Comment by Beagle** [comment]
May I move /deploy/tests/ to /tests/ and create /deploy/lib/exceptions/ and move all exceptions to it?

**Comment by tchalvak** [comment]
Sure

**Comment by tchalvak** [comment]
AC:

- move what you want, just don't break the build
- with the exception of deploy/ and /lib/ which so much of the code history revolves around

Essentially, for those two which break so much, I highly recommend approaching them in a separate, try-it-out segregated branch way so that we can decide -not- to merge those changes if too much breaks, you know?
Feasible? I dunno, but the prospect of repathing all things is almost certainly going to continuously break things, so planning out a good way to do it just makes sense.

**Comment by tchalvak** [comment]
Also, why have src and app, as opposed to just app.  Or why have src with a www in it?  Also, why do something different than the already existing namespaces?  The more I think about it, the less benefit I see in terms of energy spent on fixing the sheer nuclear fallout for a complete repathing.  Not sure why in the world you don't feel the same.

**Comment by Beagle** [comment]
Why have src? Because it's where we keep the source code to execute a build.

Why have src/app? Because the application is effectively the library of classes that house all logic. The front-controller, the configs, the datasheets, are not part of the application library.

Why do something different than the current namespaces? We wouldn't have to, because we could alias in the autoloader, but primarily because if we're building with the MVC pattern, we should have namespaces and dir structures that map to Models, Views, and Controllers.

Why don't I feel the same? Because I think it'll be a lot easier than you do, apparently.

**Comment by tchalvak** [comment]
I guess I suggest that we brainstorm or steal a platonic ideal directory structure for the whole project and then -make everything conform to that- as opposed to moving things piecemeal and organically.

But no question it'll be a PITA, for deployment, and, based on past results of -single- namespace moves, broken use statements X 50.

**Comment by tchalvak** [comment]
Wont-fix, reopen as desired.
